spring:
  datasource:
    url: jdbc:sqlserver://ITC-QMS:1433;databasename=TEST_LSB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: itcqms
    
    
mybatis:
  type-aliases-package: com.inventec.studentManagement.Pojo
  mapper-locations: classpath:static/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    


